### ISSUE TITLE
能不能具体点

### ISSUE THREAD

**Issue by nicaicaii** [rmlzy/export_jd_read#1]
小白不太会，最后一步具体怎么弄啊

**Comment by rmlzy** [comment]
你好, 你的反馈我已经收到了

最近闲下来的时候, 我会更新一个简单的版本, 同时更新一下说明文档

届时我会再次通知你, 欢迎点点 Star
________________________________
发件人: nicaicaii <notifications@github.com>
发送时间: 2021年1月19日 12:05
收件人: rmlzy/export_jd_read <export_jd_read@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [rmlzy/export_jd_read] 能不能具体点 (#1)


小白不太会，最后一步具体怎么弄啊

―

**Comment by nicaicaii** [comment]
大佬能不能加个这个啊https://gx.jd.com京东读书校园版，我用你这个他显示
 抓取出错:  您没有登录无法畅读图书

我试了一下午，终于可以运行了，npm太难了。试了好久

**Comment by rmlzy** [comment]
之前也有人问题京东校园版的问题

我这边没有京东校园版的账号, 我试着去注册, 发现只有学生可以注册

要不你加我微信, 我借用一下你的账号调试一下

[cid:8fc27515-78b3-4d18-b6f6-7c73ef9fd42e]
________________________________
发件人: nicaicaii <notifications@github.com>
发送时间: 2021年1月19日 17:09
收件人: rmlzy/export_jd_read <export_jd_read@noreply.github.com>
抄送: Jason Liu <rmlzy@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [rmlzy/export_jd_read] 能不能具体点 (#1)


大佬能不能加个这个啊https://gx.jd.com京东读书校园版，我用你这个他显示<https://gx.jd.com%E4%BA%AC%E4%B8%9C%E8%AF%BB%E4%B9%A6%E6%A0%A1%E5%9B%AD%E7%89%88%EF%BC%8C%E6%88%91%E7%94%A8%E4%BD%A0%E8%BF%99%E4%B8%AA%E4%BB%96%E6%98%BE%E7%A4%BA>
抓取出错: 您没有登录无法畅读图书

我试了一下午，终于可以运行了，npm太难了。试了好久

―

**Comment by rmlzy** [comment]
你好, 目前已支持校园版, 请更新代码后尝试一下

感谢你的支持

**Comment by rmlzy** [comment]
你好, 目前已支持校园版, 请更新代码后尝试一下

仓库地址: https://github.com/rmlzy/export_jd_read

感谢你的支持, 如果对你有帮助的话, 欢迎点点 Star

另外, 我创建了 QQ 群: 831175057

如果还有问题的话, 可以来群里问
________________________________
发件人: LIU Zhiyuan <rmlzy@outlook.com>
发送时间: 2021年1月19日 17:13
收件人: rmlzy/export_jd_read <reply@reply.github.com>
主题: 回复: [rmlzy/export_jd_read] 能不能具体点 (#1)

之前也有人问题京东校园版的问题

我这边没有京东校园版的账号, 我试着去注册, 发现只有学生可以注册

要不你加我微信, 我借用一下你的账号调试一下

[cid:8fc27515-78b3-4d18-b6f6-7c73ef9fd42e]
________________________________
发件人: nicaicaii <notifications@github.com>
发送时间: 2021年1月19日 17:09
收件人: rmlzy/export_jd_read <export_jd_read@noreply.github.com>
抄送: Jason Liu <rmlzy@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [rmlzy/export_jd_read] 能不能具体点 (#1)


大佬能不能加个这个啊https://gx.jd.com京东读书校园版，我用你这个他显示<https://gx.jd.com%E4%BA%AC%E4%B8%9C%E8%AF%BB%E4%B9%A6%E6%A0%A1%E5%9B%AD%E7%89%88%EF%BC%8C%E6%88%91%E7%94%A8%E4%BD%A0%E8%BF%99%E4%B8%AA%E4%BB%96%E6%98%BE%E7%A4%BA>
抓取出错: 您没有登录无法畅读图书

我试了一下午，终于可以运行了，npm太难了。试了好久

―
